### PR TITLE
#160056173/#160056176 Setup Redux and React Router 4

### PR DESCRIPTION
**Pull request by Veraclins**
#### What does this PR do?
- Set up react redux and react router 4 on the application
#### Description of Task to be completed?
- set up redux store
- set up agreed folder structure
- set up react router
- add sample pages to demonstrate routing
- add sample actions and reducers to use the store
- connect react router to use redux store
#### How should this be manually tested?
- Clone the repository 
- Navigate into the projects directory using `cd`
- Run 'npm install`
- Run `npm start`
- Navigate through the app and try it out (install react and redux devtools for a better experience)

#### What are the relevant pivotal tracker stories?
[#160056173](https://www.pivotaltracker.com/story/show/160056173)
[#160056176](https://www.pivotaltracker.com/story/show/160056176)
#### Screenshots (if appropriate)

screen shot 2018-09-06 at 11 49 29 am
screen shot 2018-09-06 at 11 49 41 am
screen shot 2018-09-06 at 11 49 51 am

#### Questions:
- None

### CODE REVIEW

**Review by Oluwafayokemi — COMMENTED** [review]
Nice! Can you look into the hound issue on the .js file especially! is it that the file you are trying to import is missing? 'Missing file extension for 'redux import/extensions''

**Review by madeofhuman — APPROVED** [review]
Nice job, Clinton. Very thorough.

**Review by chukwuemekachm — CHANGES_REQUESTED** [review]
Nice job @Veraclins, I see that you took your time to really study and understand the React, Redux and Router architecture. However, you added some components such as Navbar, LoginContainer e.t.c. You didn't write unit tests for them. Tests would help us assert that those components are renderable and when another team member modifies and breaks them the tests inform us of the bug. 
You also added a loginReducer which I remember from our last sync should be named an AuthReducer.
Please endeavor to unit tests the components and the reducer and also rename the reducer to authReducer.
Overall good job!

**Review by Oluwafayokemi — COMMENTED** [review]
@Veraclins What do you think about us creating a file for history and create the createBrowserHistory function there. like this https://stackoverflow.com/questions/42701129/how-to-push-to-history-in-react-router-v4. So that history can be reusable anywhere. Without having to call createBrowserHistory again?

**Comment by Veraclins** [comment]
@Oluwafayokemi, thanks for your feedback. All the hound issues were fixed before I asked for your review and the import/extensions issue is complaining that we are not adding .js and .jsx to our imports. It just required a rule in .eslinrc.json which I have since added. On the history prop, the example you cited is only necessary if you need the history object outside components. With the current configuration, history is already available as a prop to every component no matter how deeply nested it is. Once again thanks for your review.

@chukwuemekachm, thanks for your review and I love the way you make your point very clear. I am quite aware that every REAL component requires a test, however, the components I added were simply to test the routing and redux setup (as stated in the task). Obviously, they will be replaced by the REAL components for those features. It, therefore, does not make much sense to me to write tests for components that are in themselves tests. I will change the LoginReducer as well as the folder name immediately to reflect our agreed structure. Thanks for pointing it out and thanks for the feedback as a whole.

**Comment by Veraclins** [comment]
I have implemented the feedback. Thanks once again @Oluwafayokemi and @chukwuemekachm

**Comment by chukwuemekachm** [comment]
Nice job.
I see you've implemented the feedback.
Well done @Veraclins.

**Review by chukwuemekachm — APPROVED** [review]

**Review by Oluwafayokemi — APPROVED** [review]
Great Well done! @Veraclins!

**Pull request merged**
