### PR TITLE
#160056182 Completes social sign in with OAuth2.0 providers

### PR DESCRIPTION
**Pull request by chukwuemekachm**
#### What does this PR do?
- Completes social sign in with OAuth2.0 providers
#### Description of Task to be completed?
- Add SocialLoginContainer.js
- Add SocialLoginActions.js
- Modify authReducer
- Add tests for components
- Implement PO feedback on social login buttons
- Resolve prop-types validation errors
- Link to deployed [heroku-app](https://elven-ah-develop.herokuapp.com/)
#### How should this be manually tested?
- Clone the repo
- Start up command line or the terminal
- Run `npm install`
- Run `npm start`
- Your default browser will be launched, navigate to `/signup` or `/login`
- Click any social auth provider button and follow the prompt.
#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
- [#160056182](https://www.pivotaltracker.com/story/show/160056182)
#### Screenshots (if appropriate)

screen shot 2018-09-18 at 3 36 41 pm

#### Questions:
- None

### CODE REVIEW

**Review by madeofhuman — APPROVED** [review]
Nice job completing this task, @chukwuemekachm, especially with the social login test you wrote.

**Review by Veraclins — APPROVED** [review]
Nice job @chukwuemekachm, the social login works fine and the code is neat! Kudos man!

**Review by Oluwafayokemi — APPROVED** [review]
Nice Work @chukwuemekachm. Well done!

**Comment by tonymontaro** [comment]
@chukwuemekachm  Include the deployed dev link in the PR description.

**Review by tonymontaro — APPROVED** [review]
Excellent work!

**Pull request merged**
