### PR TITLE
#160587215 view all articles on landing page

### PR DESCRIPTION
**Pull request by madeofhuman**
#### What does this PR do?
- Create a dynamic landing page where users can see the articles on the site

#### Description of Task to be completed?
- create a landing page where users (logged in or not) can view the articles on the site.
- use a dynamic grid layout for this page
- display only articles with images on the landing page

#### How should this be manually tested?
- Clone the repo
- Start up command line or the terminal
- Run `npm install`
- Run `npm start`
- Your default browser will be launched, navigate to the root path`/`

#### Production url:
https://elven-ah-develop.herokuapp.com/

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- [##160587215](https://www.pivotaltracker.com/story/show/#160587215)

#### Screenshots (if appropriate)
screen shot 2018-09-27 at 11 40 49 am
screen shot 2018-09-27 at 11 40 56 am
screen shot 2018-09-27 at 11 41 01 am

#### Questions:
- None

### CODE REVIEW

**Review by yomigeek — APPROVED** [review]
Good work! Well done... I really love the user interface, the cards arrangemement, font consistency, the implementation of the functionality. Keep it up. @madeofhuman @Oluwafayokemi

**Review by Veraclins — APPROVED** [review]
This looks really cool! Good job @madeofhuman and @Oluwafayokemi. Kudos!

**Review by chukwuemekachm — APPROVED** [review]
Well done @madeofhuman  and @Oluwafayokemi on completing this task.
I really admire the work and effort you both put into this feature.
The UI looks exactly like the mockup which is very awesome.
Well done guys.

**Review by tonymontaro — APPROVED** [review]
Looks good. Great job!

**Pull request merged**
