### PR TITLE
#160056181 User Login, Password Reset Hosting the Frontend on Heroku

### PR DESCRIPTION
**Pull request by Veraclins**
#### What does this PR do?
- Add ability for users to log in and reset their password and host the application on Heroku
#### Description of Task to be completed?
- add user login feature
- add user reset password feature
- fix some CSS mix-ups
- add API proxy link for API calls in development
- implement feedback from the demo
- move query-sting module to /src
- host the app on Heroku
- add static.json to fix react router error on Heroku
#### How should this be manually tested?
- Clone the repository 
- Navigate into the projects directory using `cd elven-ah-client`
- Run `npm install`
- Run `npm start`
- Navigate to /login and /password/reset and try it out 

#### What are the relevant pivotal tracker stories?
[#160056181](https://www.pivotaltracker.com/story/show/160056181)
[#160056181](https://www.pivotaltracker.com/story/show/160056180)
#### Screenshots (if appropriate)
screen shot 2018-09-17 at 2 47 44 pm
screen shot 2018-09-17 at 2 47 53 pm
screen shot 2018-09-17 at 2 48 21 pm

#### Questions:
- None

### CODE REVIEW

**Review by chukwuemekachm — APPROVED** [review]
Good job @Veraclins on completing this task. I like that you tried to resolve all linting issues, added a loader as well as used lodash throttle to persist the state in the localStorage everytime the state is updated so that the app can boot up with the persisted state or allow reducers to initialize the state when the combine reducer returns an undefined.
A job well done.

**Review by Oluwafayokemi — COMMENTED** [review]
Nice Work @Veraclins. I noticed that onclick of the logout button, the data saved in the local storage is not cleared. Which means the user is not logged out. Do you mind checking to see what the problem is? If there is an omission or error somewhere. 
Also, the history in the index.js is already defined in the inside a history file in the util folder under the shared folder. Instead of creating the history again from index.js you could just import the history from the util folder and use it there.
Overall Awesome Work!

**Comment by Veraclins** [comment]
@Oluwafayokemi Thanks for the feedback and thanks for pointing out the issue with the logout. It has been fixed and the global history too. Once again thanks.

**Review by Oluwafayokemi — APPROVED** [review]
Awesome work! Thank you for this good job. Well done @Veraclins

**Review by madeofhuman — APPROVED** [review]
@Veraclins you kill me every time with the initiatives you take to make the product better! I love the loader component you created to mount every time `IS_LOADING` is dispatched. Great job. Your code is also clean and well structured. Keep it up.

**Pull request merged**
